### ISSUE TITLE
rss explore for rss fails with a panic

### ISSUE THREAD

**Issue by ba11b0y** [checkpoint-restore/go-criu#106]
Steps to reproduce:
 - Run `crit x <imgs_directory> rss`

Cause:
 - Panic on line https://github.com/checkpoint-restore/go-criu/blob/master/crit/explore.go#L329 due to `vmaIndex` exceeding the total length of virtual memory addresses

Traceback:

```bash
panic: runtime error: index out of range [53] with length 53

goroutine 1 [running]:
github.com/checkpoint-restore/go-criu/v6/crit.(*crit).ExploreRss(0x140001b7900)
        /Users/rahul/go/src/criu-try/go-criu/crit/explore.go:329 +0xa50
main.glob..func5(0x103453ec0?, {0x14000216300, 0x2, 0x2?})
        /Users/rahul/go/src/criu-try/go-criu/crit/cmd/cli.go:172 +0x290
github.com/spf13/cobra.(*Command).execute(0x103453ec0, {0x140002162c0, 0x2, 0x2})
        /Users/rahul/go/src/criu-try/go-criu/vendor/github.com/spf13/cobra/command.go:920 +0x5b0
github.com/spf13/cobra.(*Command).ExecuteC(0x103453060)
        /Users/rahul/go/src/criu-try/go-criu/vendor/github.com/spf13/cobra/command.go:1044 +0x35c
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/rahul/go/src/criu-try/go-criu/vendor/github.com/spf13/cobra/command.go:968
main.main()
        /Users/rahul/go/src/criu-try/go-criu/crit/cmd/cli.go:216 +0x28
```

If this seems a valid issue, I'd be glad to take this up!

**Comment by rst0git** [comment]
> Run crit x <imgs_directory> rss

@ba11b0y Thank you for opening this issue!

I'm not able to replicate this error. Could you describe how you created the checkpoint?

**Comment by ba11b0y** [comment]
I was trying to checkpoint the cron service running with systemctl as a daemon proc using
`criu dump --tree 730 --images-dir ./imgs/ --file-locks --ext-unix-sk`

where 730 is the PID of the cron service

**Comment by rst0git** [comment]
Hmm, I'm tested this on Fedora 37 with go version 1.19.6, but `crit x <imgs_directory> rss` seems to work as expected.
```
sudo ./crit/bin/crit x /tmp/test/ rss
[
    {
        "pId": 113270,
        "rss": [
            {
                "phyAddr": "555f12596000",
                "phyPages": 1,
                "vmas": [
                    {
                        "addr": "555f12596000",
                        "pages": 10
                    }
                ],
                "resource": "/usr/sbin/crond"
            },
            {
                "phyAddr": "555f125a4000",
                "phyPages": 2,
                "vmas": [
                    {
                        "addr": "555f125a4000",
                        "pages": 1
                    },
                    {
                        "addr": "555f125a5000",
                        "pages": 1
                    }
                ],
                "resource": "/usr/sbin/crond"
            },
            {
                "phyAddr": "555f125e5000",
                "phyPages": 33,
                "vmas": [
                    {
                        "addr": "555f125a6000",
                        "pages": 128
                    }
                ]
            },
            {
                "phyAddr": "555f12625000",
                "phyPages": 1,
                "vmas": [
                    {
                        "addr": "~"
                    }
                ]
            },
            {
                "phyAddr": "555f14609000",
                "phyPages": 6,
                "vmas": [
                    {
                        "addr": "555f14609000",
                        "pages": 33
                    }
                ]
            },
            {
                "phyAddr": "555f14613000",
                "phyPages": 1,
                "vmas": [
                    {
                        "addr": "~"
                    }
                ]
            },
            {
                "phyAddr": "555f14615000",
                "phyPages": 4,
                "vmas": [
                    {
                        "addr": "~"
                    }
                ]
            },
            {
                "phyAddr": "7f8090a6a000",
                "phyPages": 2,
                "vmas": [
                    {
                        "addr": "7f8090a6a000",
                        "pages": 2
                    }
                ]
            },
            {
                "phyAddr": "7f8090a74000",
                "phyPages": 1,
                "vmas": [
                    {
                        "addr": "7f8090a74000",
                        "pages": 1
                    }
                ],
                "resource": "/usr/lib64/libcap-ng.so.0.0.0"
            },
            {
                "phyAddr": "7f8090a75000",
                "phyPages": 1,
                "vmas": [
                    {
                        "addr": "7f8090a75000",
                        "pages": 1
                    }
                ]
            },
            {
                "phyAddr": "7f8090b54000",
                "phyPages": 2,
                "vmas": [
                    {
                        "addr": "7f8090b54000",
                        "pages": 1
                    },
                    {
                        "addr": "7f8090b55000",
                        "pages": 1
                    }
                ],
                "resource": "/usr/lib64/libm.so.6"
            },
            {
                "phyAddr": "7f8090b56000",
                "phyPages": 2,
                "vmas": [
                    {
                        "addr": "7f8090b56000",
                        "pages": 2
                    }
                ]
            },
            {
                "phyAddr": "7f8090b61000",
                "phyPages": 1,
                "vmas": [
                    {
                        "addr": "7f8090b61000",
                        "pages": 1
                    }
                ],
                "resource": "/usr/lib64/libeconf.so.0.4.0"
            },
            {
                "phyAddr": "7f8090bfe000",
                "phyPages": 2,
                "vmas": [
                    {
                        "addr": "7f8090bfe000",
                        "pages": 1
                    },
                    {
                        "addr": "7f8090bff000",
                        "pages": 1
                    }
                ],
                "resource": "/usr/lib64/libpcre2-8.so.0.11.0"
            },
            {
                "phyAddr": "7f8090dcf000",
                "phyPages": 6,
                "vmas": [
                    {
                        "addr": "7f8090dcf000",
                        "pages": 4
                    },
                    {
                        "addr": "7f8090dd3000",
                        "pages": 2
                    }
                ],
                "resource": "/usr/lib64/libc.so.6"
            },
            {
                "phyAddr": "7f8090dd5000",
                "phyPages": 1,
                "vmas": [
                    {
                        "addr": "7f8090dd5000",
                        "pages": 8
                    }
                ]
            },
            {
                "phyAddr": "7f8090dd9000",
                "phyPages": 4,
                "vmas": [
                    {
                        "addr": "~"
                    }
                ]
            },
            {
                "phyAddr": "7f8090dfd000",
                "phyPages": 2,
                "vmas": [
                    {
                        "addr": "7f8090dfd000",
                        "pages": 1
                    },
                    {
                        "addr": "7f8090dfe000",
                        "pages": 1
                    }
                ],
                "resource": "/usr/lib64/libaudit.so.1.0.0"
            },
            {
                "phyAddr": "7f8090e1b000",
                "phyPages": 2,
                "vmas": [
                    {
                        "addr": "7f8090e1b000",
                        "pages": 1
                    },
                    {
                        "addr": "7f8090e1c000",
                        "pages": 1
                    }
                ],
                "resource": "/usr/lib64/libpam.so.0.85.1"
            },
            {
                "phyAddr": "7f8090e46000",
                "phyPages": 2,
                "vmas": [
                    {
                        "addr": "7f8090e46000",
                        "pages": 1
                    },
                    {
                        "addr": "7f8090e47000",
                        "pages": 1
                    }
                ],
                "resource": "/usr/lib64/libselinux.so.1"
            },
            {
                "phyAddr": "7f8090e48000",
                "phyPages": 2,
                "vmas": [
                    {
                        "addr": "7f8090e48000",
                        "pages": 2
                    }
                ]
            },
            {
                "phyAddr": "7f8090e62000",
                "phyPages": 2,
                "vmas": [
                    {
                        "addr": "7f8090e62000",
                        "pages": 2
                    }
                ]
            },
            {
                "phyAddr": "7f8090e97000",
                "phyPages": 4,
                "vmas": [
                    {
                        "addr": "7f8090e97000",
                        "pages": 2
                    },
                    {
                        "addr": "7f8090e99000",
                        "pages": 2
                    }
                ],
                "resource": "/usr/lib64/ld-linux-x86-64.so.2"
            },
            {
                "phyAddr": "7ffe4f149000",
                "phyPages": 131,
                "vmas": [
                    {
                        "addr": "7ffe4f149000",
                        "pages": 131
                    }
                ]
            },
            {
                "phyAddr": "7ffe4f1da000",
                "phyPages": 2,
                "vmas": [
                    {
                        "addr": "7ffe4f1da000",
                        "pages": 2
                    }
                ]
            }
        ]
    }
]
```

**Comment by snprajwal** [comment]
Interesting, I tried this locally and it worked fine too. Nevertheless, I'll take a look at the implementation and see if there is a possibility of missing a bound check.

**Comment by snprajwal** [comment]
@rst0git is it possible for the last VMA to belong to the previous pagemap? We might have to do a bound check here if that's the case: https://github.com/checkpoint-restore/go-criu/blob/6b54af835c091f139afa14e17ea3378502fdef3d/crit/explore.go#L329-L333

If that is not possible, then this could be happening because of a corrupted checkpoint. @ba11b0y could you verify if the checkpoint was successful and `criu dump` exited with exit code 0? You can also use `criu dump -o dump.log` and examine the log file to ensure it performed the dump properly.

**Comment by snprajwal** [comment]
@rst0git this seems like a transient issue. Can we close this?

**Comment by rst0git** [comment]
I agree, let's close this issue for now.
